import type { Audience, ColourFamily, Material, ProductDetail, ProductImage } from "../schema/catalog";

/**
 * Initial catalogue, loaded by `npm run db:seed`. After the first load the database is the
 * source of truth; edit products there, not here.
 * Photos are from Unsplash (free to use under the Unsplash License); each was checked at
 * full resolution for visible third-party logos. Prices are integer cents.
 */

export type SeedCategory = { slug: string; name: string };

export type SeedProduct = {
  slug: string;
  name: string;
  /** Category slug. */
  category: string;
  audience: Audience;
  price: number;
  colour: string;
  colourFamily: ColourFamily;
  material: Material;
  description: string;
  details: ProductDetail[];
  stock: number;
  images: ProductImage[];
};

/** Unsplash CDN URL; src/lib/image-loader.ts adds the size and format per request. */
function unsplash(id: string) {
  return `https://images.unsplash.com/photo-${id}`;
}

/**
 * Gallery for a product that has a single photo: the full 4:5 shot plus close-ups cropped
 * by Unsplash's CDN around focal points (x, y in 0–1, zoom ≥ 1). `main` moves the full
 * shot's focal point when the product sits off-centre in the original.
 */
function gallery(
  id: string,
  alt: string,
  closeUps: { x: number; y: number; zoom: number; alt: string }[],
  main = { x: 0.5, y: 0.5 },
) {
  const crop = (x: number, y: number, zoom: number) =>
    `${unsplash(id)}?ar=4:5&fit=crop&crop=focalpoint&fp-x=${x}&fp-y=${y}&fp-z=${zoom}`;
  return [
    { src: crop(main.x, main.y, 1), alt },
    ...closeUps.map((c) => ({ src: crop(c.x, c.y, c.zoom), alt: c.alt })),
  ];
}

export const categories: SeedCategory[] = [
  { slug: "bags", name: "Bags" },
  { slug: "shoes", name: "Shoes" },
  { slug: "accessories", name: "Accessories" },
  { slug: "jewellery", name: "Jewellery" },
  { slug: "ready-to-wear", name: "Ready-to-wear" },
];

/**
 * Newest first: the seed gives each product a created_at one minute older than the one
 * before it, so the homepage "New this season" grid (newest 8) keeps this order.
 */
export const products: SeedProduct[] = [
  {
    slug: "top-handle-bag-teal",
    name: "Top-handle bag",
    category: "bags",
    audience: "women",
    price: 189000,
    colour: "Teal",
    colourFamily: "green",
    material: "leather",
    description:
      "A compact top-handle bag in pebbled calf leather, with a polished push-lock and a detachable shoulder strap.",
    details: [
      { term: "Material", value: "Pebbled calf leather" },
      { term: "Lining", value: "Cotton twill" },
      { term: "Hardware", value: "Gold-tone brass" },
      { term: "Size", value: "26 × 19 × 11 cm" },
    ],
    stock: 12,
    images: gallery("1594223274512-ad4803739b7c", "Teal leather top-handle bag", [
      { x: 0.5, y: 0.45, zoom: 2.2, alt: "Close-up of the handle and pebbled leather grain" },
      { x: 0.35, y: 0.6, zoom: 2.6, alt: "Close-up of the bag's gold push-lock" },
    ]),
  },
  {
    slug: "double-monk-shoe",
    name: "Double-monk shoe",
    category: "shoes",
    audience: "men",
    price: 79000,
    colour: "Tan",
    colourFamily: "brown",
    material: "leather",
    description: "Goodyear-welted double-monk straps in burnished calf, on a leather sole with a stacked heel.",
    details: [
      { term: "Upper", value: "Burnished calf leather" },
      { term: "Sole", value: "Leather, Goodyear welted" },
      { term: "Heel", value: "2.5 cm stacked leather" },
    ],
    stock: 2,
    images: gallery("1533867617858-e7b97e060509", "Pair of brown double-monk-strap leather shoes", [
      { x: 0.55, y: 0.55, zoom: 2.2, alt: "Close-up of the double buckle straps" },
    ]),
  },
  {
    slug: "round-sunglasses",
    name: "Round metal sunglasses",
    category: "accessories",
    audience: "unisex",
    price: 42000,
    colour: "Gold / green",
    colourFamily: "gold",
    material: "metal",
    description: "Thin gold-tone frames with round green lenses and adjustable nose pads. Supplied with a leather case.",
    details: [
      { term: "Frame", value: "Gold-tone metal" },
      { term: "Lenses", value: "Green, 100% UV protection" },
      { term: "Lens width", value: "49 mm" },
    ],
    stock: 18,
    images: gallery("1511499767150-a48a237f0083", "Round gold-framed sunglasses on a white surface", [
      { x: 0.5, y: 0.5, zoom: 2.4, alt: "Close-up of the gold bridge and green lenses" },
    ]),
  },
  {
    slug: "gold-hoop-earrings",
    name: "Twisted hoop earrings",
    category: "jewellery",
    audience: "women",
    price: 56000,
    colour: "Gold",
    colourFamily: "gold",
    material: "gold",
    description: "Medium hoops in a twisted rope profile, cast in recycled sterling silver with 18k gold vermeil.",
    details: [
      { term: "Material", value: "18k gold vermeil on recycled silver" },
      { term: "Diameter", value: "2.4 cm" },
      { term: "Fastening", value: "Hinged clasp" },
    ],
    stock: 0,
    images: gallery("1617038220319-276d3cfab638", "Gold twisted hoop earrings beside a pebble", [
      { x: 0.55, y: 0.55, zoom: 2.4, alt: "Close-up of the twisted hoop profile" },
    ]),
  },
  {
    slug: "leather-biker-jacket",
    name: "Leather biker jacket",
    category: "ready-to-wear",
    audience: "unisex",
    price: 345000,
    colour: "Black",
    colourFamily: "black",
    material: "leather",
    description:
      "An asymmetric biker in supple lambskin, with an off-centre zip, snap-down lapels and a belted hem.",
    details: [
      { term: "Material", value: "Lambskin leather" },
      { term: "Lining", value: "Cupro" },
      { term: "Fit", value: "True to size, cropped at the hip" },
    ],
    stock: 5,
    // Source is 1492px wide, so close-ups stay at a modest zoom.
    images: gallery("1521223890158-f9f7c3d5d504", "Black leather biker jacket worn open over a black tee", [
      { x: 0.8, y: 0.2, zoom: 1.8, alt: "Close-up of the snap-down lapel" },
      { x: 0.12, y: 0.45, zoom: 1.8, alt: "Close-up of the zipped chest pocket" },
    ]),
  },
  {
    slug: "bomber-jacket-rust",
    name: "Bomber jacket",
    category: "ready-to-wear",
    audience: "men",
    price: 128000,
    colour: "Rust",
    colourFamily: "orange",
    material: "nylon",
    description: "A lightweight bomber in washed nylon twill with ribbed trims and a two-way zip.",
    details: [
      { term: "Material", value: "Washed nylon twill" },
      { term: "Trims", value: "Ribbed wool blend" },
      { term: "Fit", value: "Relaxed" },
    ],
    stock: 9,
    images: gallery("1591047139829-d91aecb6caea", "Rust-coloured bomber jacket held up on a hanger", [
      { x: 0.5, y: 0.7, zoom: 2.2, alt: "Close-up of the zip and ribbed hem" },
    ]),
  },
  {
    slug: "floral-pump",
    name: "Floral satin pump",
    category: "shoes",
    audience: "women",
    price: 89000,
    colour: "Blue floral",
    colourFamily: "blue",
    material: "satin",
    description: "A pointed pump in printed duchess satin on a slim 10 cm heel, with a leather sole.",
    details: [
      { term: "Upper", value: "Printed duchess satin" },
      { term: "Heel", value: "10 cm" },
      { term: "Sole", value: "Leather" },
    ],
    stock: 3,
    images: gallery("1543163521-1bf539c55dd2", "Floral-print stiletto pumps against a pale blue wall", [
      { x: 0.45, y: 0.65, zoom: 2.2, alt: "Close-up of the floral satin print" },
    ]),
  },
  {
    slug: "fringed-knit-poncho",
    name: "Fringed knit poncho",
    category: "ready-to-wear",
    audience: "women",
    price: 98000,
    colour: "Ecru",
    colourFamily: "beige",
    material: "cotton",
    description: "An open-knit poncho in undyed cotton and linen, finished with a hand-knotted fringe.",
    details: [
      { term: "Material", value: "Cotton and linen" },
      { term: "Knit", value: "Open crochet stitch" },
      { term: "Size", value: "One size" },
    ],
    stock: 7,
    images: gallery("1434389677669-e08b4cac3105", "Cream open-knit poncho with fringe on a wooden hanger", [
      { x: 0.5, y: 0.75, zoom: 2.2, alt: "Close-up of the knotted fringe" },
    ]),
  },
  {
    slug: "leather-tote-tan",
    name: "Leather tote",
    category: "bags",
    audience: "unisex",
    price: 98000,
    colour: "Tan",
    colourFamily: "brown",
    material: "leather",
    description:
      "An unlined tote in waxed, vegetable-tanned leather that darkens and softens with wear, with saddle-stitched handles and brass rivets.",
    details: [
      { term: "Material", value: "Waxed vegetable-tanned leather" },
      { term: "Handles", value: "Saddle-stitched, 24 cm drop" },
      { term: "Hardware", value: "Solid brass rivets" },
      { term: "Size", value: "34 × 36 × 10 cm" },
    ],
    stock: 4,
    images: gallery("1624687943971-e86af76d57de", "Tan waxed-leather tote hanging from a white door", [
      { x: 0.33, y: 0.46, zoom: 2.4, alt: "Close-up of a brass rivet and saddle stitching on the handle" },
      { x: 0.55, y: 0.68, zoom: 2.2, alt: "Close-up of the waxed leather's natural markings" },
    ]),
  },
  {
    slug: "structured-handbag-brown",
    name: "Structured handbag",
    category: "bags",
    audience: "women",
    price: 165000,
    colour: "Chestnut",
    colourFamily: "brown",
    material: "leather",
    description:
      "A structured handbag in smooth calf leather, with a buckled front strap and a rolled top handle that keeps its shape.",
    details: [
      { term: "Material", value: "Smooth calf leather" },
      { term: "Lining", value: "Cotton twill" },
      { term: "Hardware", value: "Antique brass" },
      { term: "Size", value: "28 × 21 × 12 cm" },
    ],
    stock: 8,
    images: gallery("1691480150204-66dd1eb77391", "Chestnut leather structured handbag", [
      { x: 0.3, y: 0.55, zoom: 3, alt: "Close-up of the buckle strap" },
      { x: 0.5, y: 0.28, zoom: 3, alt: "Close-up of the rolled top handle" },
    ]),
  },
  {
    slug: "croc-top-handle-yellow",
    name: "Croc-embossed top-handle bag",
    category: "bags",
    audience: "women",
    price: 148000,
    colour: "Mustard",
    colourFamily: "yellow",
    material: "leather",
    description:
      "A small top-handle bag in croc-embossed leather, closed with a polished turn-lock. Carry it by hand or on the detachable strap.",
    details: [
      { term: "Material", value: "Croc-embossed calf leather" },
      { term: "Lining", value: "Suede" },
      { term: "Hardware", value: "Gold-tone brass" },
      { term: "Size", value: "22 × 16 × 9 cm" },
    ],
    stock: 6,
    images: gallery("1640901556395-f0e709c33494", "Mustard croc-embossed leather top-handle bag", [
      { x: 0.33, y: 0.55, zoom: 3.5, alt: "Close-up of the turn-lock and embossed grain" },
    ]),
  },
  {
    slug: "barrel-bag-burgundy",
    name: "Barrel bag",
    category: "bags",
    audience: "women",
    price: 132000,
    colour: "Burgundy",
    colourFamily: "red",
    material: "leather",
    description:
      "A rounded barrel bag in glossy burgundy leather, with twin handles and a zip that runs the full length.",
    details: [
      { term: "Material", value: "Polished calf leather" },
      { term: "Lining", value: "Cotton canvas" },
      { term: "Closure", value: "Two-way zip" },
      { term: "Size", value: "30 × 18 × 18 cm" },
    ],
    stock: 0,
    images: gallery("1713425884499-743f5372a65e", "Burgundy leather barrel bag", [
      { x: 0.5, y: 0.42, zoom: 3, alt: "Close-up of the twin handles" },
      { x: 0.22, y: 0.62, zoom: 5, alt: "Close-up of the side clasp" },
    ]),
  },
  {
    slug: "slouchy-hobo-black",
    name: "Slouchy hobo",
    category: "bags",
    audience: "women",
    price: 118000,
    colour: "Black",
    colourFamily: "black",
    material: "leather",
    description:
      "An unstructured hobo in soft nappa that slumps into shape on the shoulder. Big enough for a day, light enough to forget.",
    details: [
      { term: "Material", value: "Nappa leather" },
      { term: "Lining", value: "Unlined" },
      { term: "Strap drop", value: "24 cm" },
      { term: "Size", value: "38 × 30 × 12 cm" },
    ],
    stock: 11,
    images: gallery("1758542988969-39a10168b2ce", "Black leather slouchy hobo bag", [
      { x: 0.5, y: 0.5, zoom: 3, alt: "Close-up of the soft gathered leather" },
    ]),
  },
  {
    slug: "pebbled-satchel-grey",
    name: "Pebbled satchel",
    category: "bags",
    audience: "unisex",
    price: 142000,
    colour: "Dove grey",
    colourFamily: "grey",
    material: "leather",
    description:
      "A satchel in pebbled leather with gold-tone buckles over a magnetic flap. Top handle and a long strap.",
    details: [
      { term: "Material", value: "Pebbled calf leather" },
      { term: "Lining", value: "Cotton twill" },
      { term: "Hardware", value: "Gold-tone brass" },
      { term: "Size", value: "30 × 22 × 10 cm" },
    ],
    stock: 7,
    images: gallery("1605733513597-a8f8341084e6", "Dove grey pebbled leather satchel", [
      { x: 0.35, y: 0.55, zoom: 3.5, alt: "Close-up of the gold buckle" },
      { x: 0.5, y: 0.3, zoom: 3, alt: "Close-up of the top handle" },
    ]),
  },
  {
    slug: "leather-messenger-brown",
    name: "Leather messenger",
    category: "bags",
    audience: "men",
    price: 156000,
    colour: "Cognac",
    colourFamily: "brown",
    material: "leather",
    description:
      "A messenger in vegetable-tanned leather that darkens with wear, with two front pockets and an adjustable strap.",
    details: [
      { term: "Material", value: "Vegetable-tanned leather" },
      { term: "Lining", value: "Cotton canvas" },
      { term: "Fits", value: "13-inch laptop" },
      { term: "Size", value: "36 × 27 × 9 cm" },
    ],
    stock: 5,
    images: gallery("1657603738389-951c374b740c", "Cognac leather messenger bag", [
      { x: 0.5, y: 0.45, zoom: 3, alt: "Close-up of the front pockets" },
      { x: 0.4, y: 0.86, zoom: 4, alt: "Close-up of the strap buckle" },
    ]),
  },
  {
    slug: "leather-rucksack-tan",
    name: "Leather rucksack",
    category: "bags",
    audience: "men",
    price: 168000,
    colour: "Tan",
    colourFamily: "brown",
    material: "leather",
    description:
      "A rucksack in rugged, waxed leather with a buckled flap and a deep front pocket. Built to be used, and to look it.",
    details: [
      { term: "Material", value: "Waxed full-grain leather" },
      { term: "Lining", value: "Cotton canvas" },
      { term: "Closure", value: "Buckled flap" },
      { term: "Size", value: "40 × 30 × 14 cm" },
    ],
    stock: 2,
    images: gallery("1603504567672-bc39a18c3371", "Tan leather rucksack against a white wall", [
      { x: 0.5, y: 0.35, zoom: 3, alt: "Close-up of the front pocket" },
      { x: 0.5, y: 0.6, zoom: 3, alt: "Close-up of the strap buckles" },
    ]),
  },
  {
    slug: "buckled-briefcase-brown",
    name: "Buckled briefcase",
    category: "bags",
    audience: "men",
    price: 210000,
    colour: "Espresso",
    colourFamily: "brown",
    material: "leather",
    description:
      "A traditional briefcase in espresso leather, with two buckled straps, a top handle and a padded laptop sleeve.",
    details: [
      { term: "Material", value: "Full-grain calf leather" },
      { term: "Lining", value: "Cotton twill" },
      { term: "Fits", value: "15-inch laptop" },
      { term: "Size", value: "40 × 29 × 11 cm" },
    ],
    stock: 6,
    images: gallery("1603219527847-24c87f552a77", "Espresso leather briefcase on a wooden stool", [
      { x: 0.5, y: 0.5, zoom: 2.5, alt: "Close-up of the strap buckles" },
    ]),
  },
  {
    slug: "patent-slingback-black",
    name: "Patent slingback",
    category: "shoes",
    audience: "women",
    price: 69000,
    colour: "Black",
    colourFamily: "black",
    material: "leather",
    description:
      "A pointed slingback in crinkled patent leather on a low, sculpted heel. An elastic strap keeps it in place.",
    details: [
      { term: "Upper", value: "Crinkled patent leather" },
      { term: "Lining", value: "Leather" },
      { term: "Heel", value: "4 cm" },
      { term: "Sole", value: "Leather" },
    ],
    stock: 9,
    images: gallery("1789110519431-0a9bf0af5074", "Black patent leather slingback with a sculpted heel", [
      { x: 0.3, y: 0.5, zoom: 3, alt: "Close-up of the sculpted heel and slingback strap" },
    ]),
  },
  {
    slug: "strappy-sandal-silver",
    name: "Strappy sandal",
    category: "shoes",
    audience: "women",
    price: 74000,
    colour: "Silver",
    colourFamily: "silver",
    material: "leather",
    description: "A high sandal in metallic leather, with a wraparound ankle strap that zips at the back.",
    details: [
      { term: "Upper", value: "Metallic leather" },
      { term: "Lining", value: "Leather" },
      { term: "Heel", value: "10 cm" },
      { term: "Fastening", value: "Back zip" },
    ],
    stock: 12,
    images: gallery("1789110519500-00ec76088f81", "Silver strappy high-heel sandals", [
      { x: 0.55, y: 0.45, zoom: 3, alt: "Close-up of the straps" },
    ]),
  },
  {
    slug: "cross-strap-pump-black",
    name: "Cross-strap pump",
    category: "shoes",
    audience: "women",
    price: 64000,
    colour: "Black / ecru",
    colourFamily: "black",
    material: "leather",
    description:
      "A round-toe pump with crossed ankle straps, set on a block heel wrapped in a black and ecru woven pattern.",
    details: [
      { term: "Upper", value: "Calf leather" },
      { term: "Heel", value: "6 cm, woven raffia" },
      { term: "Lining", value: "Leather" },
      { term: "Fastening", value: "Buckle" },
    ],
    stock: 9,
    images: gallery("1789110519420-21e30de24a82", "Black cross-strap pump with a woven geometric block heel", [
      { x: 0.4, y: 0.5, zoom: 3, alt: "Close-up of the crossed straps" },
    ]),
  },
  {
    slug: "slouch-boot-black",
    name: "Slouch boot",
    category: "shoes",
    audience: "women",
    price: 112000,
    colour: "Black",
    colourFamily: "black",
    material: "leather",
    description: "A knee boot in soft leather that folds down the shaft, on a slim block heel.",
    details: [
      { term: "Upper", value: "Soft calf leather" },
      { term: "Shaft height", value: "38 cm" },
      { term: "Heel", value: "7 cm" },
      { term: "Sole", value: "Rubber" },
    ],
    stock: 6,
    images: gallery("1763661300203-aa3e2702f510", "Black leather slouch boots", [
      { x: 0.5, y: 0.4, zoom: 3, alt: "Close-up of the slouched shaft" },
    ]),
  },
  {
    slug: "chelsea-boot-brown",
    name: "Chelsea boot",
    category: "shoes",
    audience: "men",
    price: 89000,
    colour: "Dark brown",
    colourFamily: "brown",
    material: "leather",
    description: "A Chelsea boot in burnished calf leather, with elastic side panels and a pull tab at the heel.",
    details: [
      { term: "Upper", value: "Burnished calf leather" },
      { term: "Lining", value: "Leather" },
      { term: "Sole", value: "Leather with rubber heel" },
      { term: "Construction", value: "Goodyear welted" },
    ],
    stock: 10,
    images: gallery("1777987601677-3059be0e1388", "Dark brown leather Chelsea boots", [
      { x: 0.6, y: 0.3, zoom: 3, alt: "Close-up of the elastic side panel" },
    ]),
  },
  {
    slug: "penny-loafer-brown",
    name: "Penny loafer",
    category: "shoes",
    audience: "men",
    price: 72000,
    colour: "Brown",
    colourFamily: "brown",
    material: "leather",
    description: "A classic penny loafer in grained leather, with a moccasin toe and a stitched saddle strap.",
    details: [
      { term: "Upper", value: "Grained calf leather" },
      { term: "Lining", value: "Leather" },
      { term: "Sole", value: "Leather" },
      { term: "Construction", value: "Blake stitched" },
    ],
    stock: 8,
    images: gallery("1675947258177-aa8120ddefa3", "Brown leather penny loafers on white", [
      { x: 0.5, y: 0.3, zoom: 2.5, alt: "Close-up of the penny strap" },
    ]),
  },
  {
    slug: "polished-loafer-tan",
    name: "Polished loafer",
    category: "shoes",
    audience: "men",
    price: 78000,
    colour: "Tan",
    colourFamily: "brown",
    material: "leather",
    description: "A loafer in hand-burnished tan leather, darker at the toe and heel, on a stacked leather heel.",
    details: [
      { term: "Upper", value: "Hand-burnished calf leather" },
      { term: "Lining", value: "Leather" },
      { term: "Sole", value: "Leather" },
      { term: "Heel", value: "Stacked leather" },
    ],
    stock: 0,
    images: gallery("1777987601447-266e128de448", "Tan polished leather loafers on a black stool", [
      { x: 0.5, y: 0.35, zoom: 3, alt: "Close-up of the burnished toe" },
    ]),
  },
  {
    slug: "derby-shoe-tan",
    name: "Derby shoe",
    category: "shoes",
    audience: "men",
    price: 68000,
    colour: "Tan",
    colourFamily: "brown",
    material: "leather",
    description: "A plain derby in smooth tan leather with open lacing, made to dress up or down.",
    details: [
      { term: "Upper", value: "Smooth calf leather" },
      { term: "Lining", value: "Leather" },
      { term: "Sole", value: "Rubber" },
      { term: "Laces", value: "Waxed cotton" },
    ],
    stock: 14,
    images: gallery("1625357165350-bdbcb6d7d524", "Tan leather derby shoes in hard sunlight", [
      { x: 0.3, y: 0.6, zoom: 3, alt: "Close-up of the open lacing" },
    ]),
  },
  {
    slug: "zip-pouch-black",
    name: "Zip pouch",
    category: "accessories",
    audience: "men",
    price: 32000,
    colour: "Black",
    colourFamily: "black",
    material: "leather",
    description: "A flat pouch in grained leather for cards, cables and keys, with a wraparound zip.",
    details: [
      { term: "Material", value: "Grained calf leather" },
      { term: "Lining", value: "Cotton" },
      { term: "Closure", value: "Metal zip" },
      { term: "Size", value: "21 × 14 cm" },
    ],
    stock: 15,
    images: gallery("1657603297584-2e7f8c13b5bc", "Black leather zip pouch", [
      { x: 0.45, y: 0.6, zoom: 4, alt: "Close-up of the zip pull" },
    ]),
  },
  {
    slug: "browline-sunglasses-black",
    name: "Browline sunglasses",
    category: "accessories",
    audience: "unisex",
    price: 36000,
    colour: "Black",
    colourFamily: "black",
    material: "acetate",
    description: "Browline sunglasses with an acetate brow, a fine metal rim and grey gradient lenses.",
    details: [
      { term: "Frame", value: "Acetate and metal" },
      { term: "Lenses", value: "Grey gradient, UV400" },
      { term: "Comes with", value: "Leather case" },
    ],
    stock: 20,
    images: gallery("1584036553516-bf83210aa16c", "Black browline sunglasses with gradient lenses", [
      { x: 0.72, y: 0.45, zoom: 4, alt: "Close-up of the acetate temple" },
    ]),
  },
  {
    slug: "braided-belt-brown",
    name: "Braided belt",
    category: "accessories",
    audience: "men",
    price: 26000,
    colour: "Brown",
    colourFamily: "brown",
    material: "leather",
    description: "A braided leather belt that fastens at any point along its length, with a brushed metal buckle.",
    details: [
      { term: "Material", value: "Braided calf leather" },
      { term: "Buckle", value: "Brushed metal" },
      { term: "Width", value: "3.5 cm" },
    ],
    stock: 18,
    images: gallery("1711443982852-b3df5c563448", "Brown braided leather belts", [
      { x: 0.5, y: 0.6, zoom: 3, alt: "Close-up of the buckle" },
    ]),
  },
  {
    slug: "suede-belt-olive",
    name: "Suede belt",
    category: "accessories",
    audience: "unisex",
    price: 25000,
    colour: "Olive",
    colourFamily: "green",
    material: "suede",
    description: "A wide belt in olive suede with an antique brass buckle.",
    details: [
      { term: "Material", value: "Suede" },
      { term: "Buckle", value: "Antique brass" },
      { term: "Width", value: "4 cm" },
    ],
    stock: 13,
    images: gallery("1752386223406-b3d94092d790", "Olive suede belt with a brass buckle", [
      { x: 0.3, y: 0.55, zoom: 3, alt: "Close-up of the brass buckle" },
    ]),
  },
  {
    slug: "straw-trilby",
    name: "Straw trilby",
    category: "accessories",
    audience: "men",
    price: 29000,
    colour: "Natural / navy and red",
    colourFamily: "beige",
    material: "mixed",
    description: "A trilby in tightly woven straw with a short brim and a navy, red and white grosgrain band.",
    details: [
      { term: "Material", value: "Paper straw" },
      { term: "Band", value: "Grosgrain ribbon" },
      { term: "Brim", value: "4.5 cm" },
    ],
    stock: 1,
    images: gallery("1725398807874-948f9721aad9", "Natural straw trilby with a striped band", [
      { x: 0.45, y: 0.4, zoom: 3, alt: "Close-up of the striped grosgrain band" },
    ]),
  },
  {
    slug: "wool-beret-red",
    name: "Wool beret",
    category: "accessories",
    audience: "women",
    price: 25000,
    colour: "Red",
    colourFamily: "red",
    material: "wool",
    description: "A classic beret in felted merino wool, with a leather-trimmed band.",
    details: [
      { term: "Material", value: "Felted merino wool" },
      { term: "Trim", value: "Leather" },
      { term: "Size", value: "One size" },
    ],
    stock: 16,
    images: gallery("1778865575946-4d26642a0323", "Red wool beret on a black mannequin head", [
      { x: 0.5, y: 0.3, zoom: 2.5, alt: "Close-up of the felted wool" },
    ]),
  },
  {
    slug: "hair-claw-gold",
    name: "Hair claw",
    category: "accessories",
    audience: "women",
    price: 25000,
    colour: "Gold",
    colourFamily: "gold",
    material: "metal",
    description: "An openwork hair claw in gold-tone metal with a strong spring hinge.",
    details: [
      { term: "Material", value: "Gold-plated brass" },
      { term: "Length", value: "9 cm" },
    ],
    stock: 22,
    images: gallery("1744177762258-c98418b7a4eb", "Gold-tone metal hair claw", [
      { x: 0.5, y: 0.65, zoom: 3, alt: "Close-up of the spring hinge" },
    ]),
  },
  {
    slug: "tortoiseshell-hair-claw",
    name: "Tortoiseshell hair claw",
    category: "accessories",
    audience: "women",
    price: 25000,
    colour: "Tortoiseshell",
    colourFamily: "brown",
    material: "acetate",
    description: "A hair claw cut from tortoiseshell acetate, polished by hand.",
    details: [
      { term: "Material", value: "Cellulose acetate" },
      { term: "Length", value: "11 cm" },
    ],
    stock: 25,
    images: gallery("1635423759716-53ccaa71b3fa", "Tortoiseshell acetate hair claw", [
      { x: 0.5, y: 0.5, zoom: 2, alt: "Close-up of the teeth" },
    ]),
  },
  {
    slug: "wire-sunglasses-gold",
    name: "Wire sunglasses",
    category: "accessories",
    audience: "women",
    price: 34000,
    colour: "Gold / brown",
    colourFamily: "gold",
    material: "metal",
    description: "Small round sunglasses on a fine gold-tone wire frame, with brown gradient lenses.",
    details: [
      { term: "Frame", value: "Gold-plated metal" },
      { term: "Lenses", value: "Brown gradient, UV400" },
      { term: "Comes with", value: "Leather case" },
    ],
    stock: 10,
    images: gallery("1649119161997-00ffc8c24e11", "Gold wire round sunglasses with brown lenses", [
      { x: 0.8, y: 0.45, zoom: 4, alt: "Close-up of the tortoiseshell temple tip" },
    ]),
  },
  {
    slug: "butterfly-brooch",
    name: "Butterfly brooch",
    category: "jewellery",
    audience: "women",
    price: 48000,
    colour: "Gold / crystal",
    colourFamily: "gold",
    material: "mixed",
    description: "A butterfly brooch set with baguette-cut crystals in a gold-plated frame.",
    details: [
      { term: "Material", value: "Gold-plated brass, glass crystals" },
      { term: "Size", value: "6 × 5 cm" },
      { term: "Fastening", value: "Pin and safety catch" },
    ],
    stock: 7,
    images: gallery("1693834084392-fa61a52a81c0", "Gold and crystal butterfly brooch on black cloth", [
      { x: 0.6, y: 0.45, zoom: 2, alt: "Close-up of the baguette crystals" },
    ]),
  },
  {
    slug: "heart-drop-earrings-blue",
    name: "Heart drop earrings",
    category: "jewellery",
    audience: "women",
    price: 26000,
    colour: "Sapphire blue",
    colourFamily: "blue",
    material: "mixed",
    description: "Faceted blue crystal hearts on gold-plated hooks.",
    details: [
      { term: "Material", value: "Glass crystal, gold-plated silver" },
      { term: "Drop", value: "3 cm" },
      { term: "Fastening", value: "Hook" },
    ],
    stock: 14,
    images: gallery("1630019852942-f89202989a59", "Blue crystal heart drop earrings on gold hooks", [
      { x: 0.5, y: 0.55, zoom: 2.5, alt: "Close-up of the faceted hearts" },
    ]),
  },
  {
    slug: "pave-crossover-ring",
    name: "Pavé crossover ring",
    category: "jewellery",
    audience: "women",
    price: 58000,
    colour: "Silver",
    colourFamily: "silver",
    material: "silver",
    description: "Two pavé-set bands that cross at the front, in sterling silver.",
    details: [
      { term: "Material", value: "Sterling silver, cubic zirconia" },
      { term: "Band width", value: "6 mm at the front" },
    ],
    stock: 9,
    images: gallery("1589674781759-c21c37956a44", "Silver pavé crossover ring", [
      { x: 0.5, y: 0.5, zoom: 2, alt: "Close-up of the pavé setting" },
    ]),
  },
  {
    slug: "half-moon-earrings",
    name: "Half-moon earrings",
    category: "jewellery",
    audience: "women",
    price: 39000,
    colour: "Silver / gold",
    colourFamily: "silver",
    material: "mixed",
    description: "Long drop earrings with etched half-moon pendants, hung from coiled gold-tone wire.",
    details: [
      { term: "Material", value: "Silver-tone and gold-tone brass" },
      { term: "Drop", value: "7 cm" },
      { term: "Fastening", value: "Hook" },
    ],
    stock: 11,
    images: gallery("1721722299497-882954bada45", "Etched half-moon drop earrings on a blue background", [
      { x: 0.5, y: 0.6, zoom: 2, alt: "Close-up of the etched circles" },
    ]),
  },
  {
    slug: "pearl-stud-earrings",
    name: "Pearl studs",
    category: "jewellery",
    audience: "women",
    price: 29000,
    colour: "Ivory",
    colourFamily: "white",
    material: "mixed",
    description: "Round freshwater pearl studs on gold-plated posts.",
    details: [
      { term: "Material", value: "Freshwater pearls, gold-plated silver" },
      { term: "Pearl size", value: "10 mm" },
      { term: "Fastening", value: "Butterfly back" },
    ],
    stock: 19,
    images: gallery("1704957205327-9fbd44d683b7", "Pearl stud earrings beside a pearl strand", [
      { x: 0.4, y: 0.6, zoom: 2, alt: "Close-up of the pearl studs" },
    ]),
  },
  {
    slug: "steel-band-rings",
    name: "Brushed band ring",
    category: "jewellery",
    audience: "men",
    price: 25000,
    colour: "Gunmetal",
    colourFamily: "grey",
    material: "metal",
    description: "A wide band in brushed stainless steel, with a polished centre line.",
    details: [
      { term: "Material", value: "Stainless steel" },
      { term: "Width", value: "8 mm" },
    ],
    stock: 17,
    images: gallery("1565206077209-0e7e57b6c152", "Two brushed steel band rings", [
      { x: 0.5, y: 0.55, zoom: 3, alt: "Close-up of the brushed finish" },
    ], { x: 0.35, y: 0.6 }),
  },
  {
    slug: "coin-charm-necklace",
    name: "Coin charm necklace",
    category: "jewellery",
    audience: "unisex",
    price: 64000,
    colour: "Gold",
    colourFamily: "gold",
    material: "gold",
    description: "A fine figaro chain hung with hammered coin charms, in 9-carat gold.",
    details: [
      { term: "Material", value: "9-carat gold" },
      { term: "Length", value: "45 cm" },
      { term: "Fastening", value: "Lobster clasp" },
    ],
    stock: 5,
    images: gallery("1717282924526-07a7373bb142", "Gold chain necklace with hammered coin charms", [
      { x: 0.5, y: 0.55, zoom: 2.5, alt: "Close-up of a hammered coin charm" },
    ]),
  },
  {
    slug: "sleeveless-top-black",
    name: "Sleeveless top",
    category: "ready-to-wear",
    audience: "women",
    price: 42000,
    colour: "Black",
    colourFamily: "black",
    material: "cotton",
    description: "A sleeveless top in crisp cotton poplin, with a round neck and a zip at the back.",
    details: [
      { term: "Material", value: "Cotton poplin" },
      { term: "Fit", value: "Relaxed" },
      { term: "Fastening", value: "Back zip" },
      { term: "Care", value: "Machine wash 30°" },
    ],
    stock: 12,
    images: gallery("1519554318711-aaf73ece6ff9", "Black sleeveless top on a grey hanger", [
      { x: 0.5, y: 0.35, zoom: 2.5, alt: "Close-up of the neckline" },
    ]),
  },
  {
    slug: "knit-sweater-rust",
    name: "Knit sweater",
    category: "ready-to-wear",
    audience: "women",
    price: 56000,
    colour: "Rust",
    colourFamily: "orange",
    material: "wool",
    description: "A hand-finished sweater in soft lambswool, with ribbed cuffs and hem.",
    details: [
      { term: "Material", value: "Lambswool" },
      { term: "Fit", value: "Relaxed" },
      { term: "Care", value: "Hand wash" },
    ],
    stock: 8,
    images: gallery("1773747203071-81d53e35c41a", "Rust knit sweater laid flat", [
      { x: 0.4, y: 0.35, zoom: 2.5, alt: "Close-up of the knit" },
    ]),
  },
  {
    slug: "slip-dress-black",
    name: "Slip dress",
    category: "ready-to-wear",
    audience: "women",
    price: 98000,
    colour: "Black",
    colourFamily: "black",
    material: "satin",
    description: "A bias-cut slip dress in heavy satin with fine adjustable straps. It falls to the ankle.",
    details: [
      { term: "Material", value: "Satin" },
      { term: "Fit", value: "Bias cut" },
      { term: "Length", value: "Ankle" },
      { term: "Care", value: "Dry clean" },
    ],
    stock: 2,
    images: gallery("1594739033447-80ab21e24b4c", "Model in a black slip dress", [
      { x: 0.5, y: 0.45, zoom: 2, alt: "Close-up of the bodice and straps" },
    ]),
  },
  {
    slug: "denim-jacket-shearling",
    name: "Denim jacket",
    category: "ready-to-wear",
    audience: "unisex",
    price: 88000,
    colour: "Light wash",
    colourFamily: "blue",
    material: "cotton",
    description: "A light-wash denim jacket with a removable shearling collar and two button-flap pockets.",
    details: [
      { term: "Material", value: "Cotton denim" },
      { term: "Collar", value: "Shearling, removable" },
      { term: "Fit", value: "Regular" },
    ],
    stock: 9,
    images: gallery("1543076447-215ad9ba6923", "Light-wash denim jacket with a shearling collar on a hook", [
      { x: 0.55, y: 0.55, zoom: 4, alt: "Close-up of the chest pocket" },
    ]),
  },
  {
    slug: "leather-jacket-brown",
    name: "Leather jacket",
    category: "ready-to-wear",
    audience: "men",
    price: 289000,
    colour: "Cognac",
    colourFamily: "brown",
    material: "leather",
    description: "A belted leather jacket in supple cognac lambskin, cut long enough to cover the hip.",
    details: [
      { term: "Material", value: "Lambskin leather" },
      { term: "Lining", value: "Cupro" },
      { term: "Fit", value: "Regular" },
      { term: "Care", value: "Specialist leather clean" },
    ],
    stock: 4,
    images: gallery("1623854156816-4c4fc355ffc7", "Cognac leather jacket hanging on a wall peg", [
      { x: 0.5, y: 0.5, zoom: 3, alt: "Close-up of the leather and pockets" },
    ]),
  },
  {
    slug: "overcoat-camel",
    name: "Overcoat",
    category: "ready-to-wear",
    audience: "men",
    price: 248000,
    colour: "Camel",
    colourFamily: "beige",
    material: "wool",
    description: "A single-breasted overcoat in camel wool, cut long and loose to wear over tailoring or knitwear.",
    details: [
      { term: "Material", value: "Wool and cashmere" },
      { term: "Lining", value: "Cupro" },
      { term: "Fit", value: "Relaxed" },
      { term: "Length", value: "Below the knee" },
    ],
    stock: 6,
    images: gallery("1619603364904-c0498317e145", "Model in a camel overcoat and turtleneck", [
      { x: 0.45, y: 0.55, zoom: 4, alt: "Close-up of the horn button" },
      { x: 0.5, y: 0.35, zoom: 3, alt: "Close-up of the notched lapel" },
    ]),
  },
  {
    slug: "merino-v-neck",
    name: "Merino V-neck",
    category: "ready-to-wear",
    audience: "men",
    price: 38000,
    colour: "Charcoal",
    colourFamily: "grey",
    material: "wool",
    description: "A fine-gauge V-neck in extra-fine merino, light enough to layer under a jacket.",
    details: [
      { term: "Material", value: "Extra-fine merino wool" },
      { term: "Gauge", value: "18" },
      { term: "Fit", value: "Regular" },
      { term: "Care", value: "Machine wash wool cycle" },
    ],
    stock: 7,
    images: gallery("1548768041-2fceab4c0b85", "Folded fine-knit V-neck jumpers in charcoal, grey and camel", [
      { x: 0.5, y: 0.45, zoom: 2.5, alt: "Close-up of the fine knit" },
    ]),
  },
];
